repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test] # optional: list of Conventional Commits types to allow e.g. [feat, fix, ci, chore, test]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      -   id: end-of-file-fixer
      -   id: trailing-whitespace
      -   id: check-added-large-files

  - repo: local
    hooks:
    - id: regula-cfn
      name: Regula for CloudFormation
      entry: regula run -f tap -t cfn
      language: system
      files: .*\.(json|yml|yaml)$

  - repo: local
    hooks:
    - id: regula-tf
      name: Regula for Terraform HCL
      entry: regula run -f tap -t tf
      language: system
      files: .*(tf)

  - repo: https://github.com/aws-cloudformation/cfn-python-lint
    rev: v0.84.0
    hooks:
      - id: cfn-python-lint
        files: .*\.(json|yml|yaml)$

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: infracost_breakdown

  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.8' # change to tag or sha
    hooks:
      -   id: checkov
          name: Checkov
          description: This hook runs checkov.
          entry: checkov -d .
          language: python
          pass_filenames: false
          always_run: false
          files: .*(yaml)$
          exclude: \.+.terraform\/.*$
          require_serial: true
          args: [--soft-fail]

exclude: ^(^\.pre-commit-config\.yaml$|^\.github/workflows\/.*$)
