AWSTemplateFormatVersion: "2010-09-09"
Resources:
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22

  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 192.168.1.1/32
Outputs:
  MySSHSecurityGroup:
    Description: A reference to the created SSHSecurityGroup
    Value: !Ref SSHSecurityGroup
    Export:
      Name: AccountSSHSecurityGroup

  MyServerSecurityGroup:
    Description: A reference to the created ServerSecurityGroup
    Value: !Ref ServerSecurityGroup
    Export:
      Name: AccountServerSecurityGroup
