AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  AvailabilityZoneA:
    Type: String
    Default: eu-west-1a

  AvailabilityZoneB:
    Type: String
    Default: eu-west-1b
Resources:
  MyVPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  PublicSubnetA:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '10.0.2.0/24'
      AvailabilityZone: !Ref AvailabilityZoneA

  PublicSubnetB:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref MyVPC
      CidrBlock: '10.0.3.0/24'
      AvailabilityZone: !Ref AvailabilityZoneB
